### ISSUE TITLE
2024/12/11Expires after game update

### ISSUE THREAD

**Issue by ddacd7** [nyfair/AGA-Panty#1]
Expires after game update

**Comment by nyfair** [comment]
Cannot reproduce, can you have a look at the latest [BepInEx5 x64](https://github.com/BepInEx/BepInEx/releases/tag/v5.4.23.2) ?
![Untitled](https://github.com/user-attachments/assets/bdd50fe4-f7f0-4712-bec2-3594c272f780)

**Comment by ddacd7** [comment]
If I click directly on \user\alicegearaegisexe\alice_main
The BepInEx window will appear normally (you will be unable to log in to the game)
However, if you log in to the game using DMMPLAYER, it will become invalid.

**Comment by ddacd7** [comment]
I ended up deleting the entire folder and reinstalling the game, and it's now working fine.Thank you
